### ISSUE TITLE
Add Social Media Sharing Buttons

### ISSUE THREAD

**Issue by Arunesh-Tiwari** [Arunesh-Tiwari/minimal-blog-template#3]
**Description:**
Implement social media sharing buttons to allow users to easily share blog posts on platforms like Facebook, Twitter, and LinkedIn. The buttons should be visually integrated into the blog's layout and responsive for mobile devices.

**Additional Notes:**
- Use popular libraries or plugins to ensure compatibility.
- Ensure buttons are tested across different browsers and devices.

**Comment by Joshua-Vankayalapati** [comment]
Hi Arunesh,

Here's a preview of social sharing buttons.

3D buttons and code compatible on different platforms and browsers.
- Applied 3D and glossy effects for a modern look.
- Ensured buttons are styled consistently and are responsive.
- Added dynamic sharing URLs based on the current page or blog post.

![sharebuttons](https://github.com/user-attachments/assets/d619c04a-174e-4aad-a579-89a5ef62713a)
![iconsharebtns](https://github.com/user-attachments/assets/7ae37e58-aa56-400b-aa13-42bf20d027af)


Please assign me if you'd like me to continue with this.

Regards,
Josh

**Comment by Arunesh-Tiwari** [comment]
Thanks @Joshua-Vankayalapati, I'm assigning it to you, go ahead.
![WhatsApp Image 2024-09-10 at 19 30 31](https://github.com/user-attachments/assets/259bc947-3373-49c1-a103-3cf3c997c6cd)
I would recommend to add social media sharing button in the above directed section.

**Comment by Joshua-Vankayalapati** [comment]
Added the buttons and submitted it for review. Please check.
